# GitHub Sponsors funding configuration
# See https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository for more information

github: [Cheemsdoge28]
ko_fi: cheemsdoge
# custom: ["https://www.buymeacoffee.com/yourid"]
